services:
  courses-db:
    container_name: courses-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: courses
      PGDATA: /pg
    volumes:
      - ./data/pg:/pg